# Generated by Django 6.1 on 2026-08-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('age', models.PositiveBigIntegerField(default=12)),
                ('total', models.BigIntegerField()),
                ('height', models.FloatField(blank=True, null=True)),
                ('married', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
